"""updating schema for instagram

Revision ID: 6830a41d0bbd
Revises: 8158972fe2b5
Create Date: 2025-06-10 02:13:42.115015

"""
from typing import Sequence, Union
from sqlmodel.sql.sqltypes import AutoString
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6830a41d0bbd'
down_revision: Union[str, None] = '8158972fe2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('instagram_page_access_token', AutoString(), nullable=True))
    op.add_column('user', sa.Column('instagram_business_account_id', AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'instagram_business_account_id')
    op.drop_column('user', 'instagram_page_access_token')
    # ### end Alembic commands ###
