"""updating schema

Revision ID: 8158972fe2b5
Revises: 9a5c99cfa1ba
Create Date: 2025-06-08 14:28:10.860785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '8158972fe2b5'
down_revision: Union[str, None] = '9a5c99cfa1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('twitter_access_token_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitter_access_token_secret')
    op.drop_column('user', 'twitter_access_token')
    # ### end Alembic commands ###
