"""updating schema for youtube

Revision ID: e9b2670fb144
Revises: 6a4e36bcdc45
Create Date: 2025-06-12 01:42:42.607927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = 'e9b2670fb144'
down_revision: Union[str, None] = '6a4e36bcdc45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduledpost_status'), table_name='scheduledpost')
    op.drop_table('scheduledpost')
    op.add_column('user', sa.Column('youtube_access_token', AutoString(), nullable=True))
    op.add_column('user', sa.Column('youtube_channel_id', AutoString(), nullable=True))
    op.add_column('user', sa.Column('youtube_refresh_token', AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'youtube_refresh_token')
    op.drop_column('user', 'youtube_channel_id')
    op.drop_column('user', 'youtube_access_token')
    op.create_table('scheduledpost',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('media_paths', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('scheduledpost_pkey'))
    )
    op.create_index(op.f('ix_scheduledpost_status'), 'scheduledpost', ['status'], unique=False)
    # ### end Alembic commands ###
